feat(examples): Introduce Playwright (Firefox) example
unikraft-cloud/examples pull request #129
Opened 2024-11-22 21:47 UTC by razvand

Introduce a Playwright (Firefox) example to be deployed on Unikraft Cloud. It uses the `base-compat:latest` image.

Add:

* `Kraftfile`: build / run rules
* `Dockerfile`: placeholder to extract the filesystem
* `package.json`: NPM configuration file
* `server.js`: implementation of Node server
* `wrapper.sh`: helper script to start the Node server
* `README.md`: document how to use
* `.dockerignore` / `.gitignore`: ignore generated files

2024-11-24 07:58 UTC, craciunoiuc commented on node-playwright-firefox/Dockerfile
> +    apt-get -yqq install \
`--no-install-recommends` can be added also

2024-11-24 08:01 UTC, craciunoiuc approved these changes
All good here. Thanks! Only one optional comment from my side.

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2025-01-27 08:08 UTC, razvand commented on node-playwright-firefox/Dockerfile
> +    apt-get -yqq install \
I wouldn't do it at this point, because the other `Dockerfile`s aren't using this. I would aim for consistency, and we could create a PR to use the `--no-install-recommends` options for all files.

2025-01-27 09:23 UTC, craciunoiuc commented
Checked again, all good

2025-01-29 08:02 UTC, craciunoiuc requested changes

2025-01-29 08:02 UTC, craciunoiuc commented on .github/workflows/example-node-playwright-firefox-staging.yaml
> +        curl -Lv --fail-with-body --max-time 10 https://node-playwright-firefox-${GITHUB_RUN_ID}.${UKC_METRO}.kraft.host/?page=https://google.com
```suggestion
        curl -Lv --fail-with-body --max-time 10 "https://node-playwright-firefox-${GITHUB_RUN_ID}.${UKC_METRO}.kraft.host/?page=https://google.com"
```

2025-01-29 08:02 UTC, craciunoiuc commented on .github/workflows/example-node-playwright-firefox-stable.yaml
> +        curl -Lv --fail-with-body --max-time 10 https://node-playwright-firefox-${GITHUB_RUN_ID}.${UKC_METRO}.kraft.host/?page=https://google.com
```suggestion
        curl -Lv --fail-with-body --max-time 10 "https://node-playwright-firefox-${GITHUB_RUN_ID}.${UKC_METRO}.kraft.host/?page=https://google.com"
```

2025-01-29 11:43 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>
Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2025-01-29 11:43 UTC, merged